services:
  - type: web
    name: todianedev
    buildCommand: ./build.sh
    startCommand: gunicorn todianedev.wsgi --bind 0.0.0.0:$PORT
    env:
      - key: DJANGO_SETTINGS_MODULE
        value: "todianedev.settings"
    healthCheckPath: "/"

  - name: worker
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A todianedev worker --loglevel=INFO

build:
  dockerfile: Dockerfile
